/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webeye_photomaster_jni_ImageCompressor */

#ifndef _Included_com_webeye_photomaster_jni_ImageCompressor
#define _Included_com_webeye_photomaster_jni_ImageCompressor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_webeye_photomaster_jni_ImageCompressor
 * Method:    compressJpeg
 * Signature: (ZI)I
 */
JNIEXPORT jint JNICALL Java_com_webeye_photomaster_jni_ImageCompressor_compressJpeg
  (JNIEnv *, jclass, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
